kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
      <h1>Welcome</h1>
      <br/>
      <h1>Hi! I got deployed in {{ .Values.env.name }} Environment using Helm Chart</h1>
    </html>
  