apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-pods
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol | default "TCP" }}
